### ISSUE TITLE
it's broken

### ISSUE THREAD

**Issue by mjlbach** [dundargoc/mjlbach-lint-workflow#29]
### Neovim Version

idk, I installed via the AUR

### Operating system/version:

arch (btw)

### Terminal name/version:

custom patched version of ST, see my git repo for patches

### TERM environment variable

TERM

### Installation

aur

### Reproduce

idk, I opened a file and everything was broken

### Vim

.

### Expected behavior

It wasn't broken

### Actual behavior

this software sucks

**Comment by mjlbach** [comment]
why will you not fix, I am going back to vscode. neovim is bad software.

**Comment by dundargoc** [comment]
Patch upstreams pls
