### ISSUE TITLE
dd

### ISSUE THREAD

**Issue by dundargoc** [dundargoc/mjlbach-lint-workflow#30]
### Neovim Version

djf

### Operating system/version:

j

### Terminal name/version:

f

### TERM environment variable

ddj

### Installation

ff

### 

- [x] Please check the box if it's possible to reproduce the bug with `nvim --clean` as well

**Comment by Maverun** [comment]
Terrible report, please close this

**Comment by dundargoc** [comment]
I do what I want it's my hot body.

**Comment by dundargoc** [comment]
gg
