### ISSUE TITLE
instruction unclear, accidentally opened a portal

### ISSUE THREAD

**Issue by elianiva** [dundargoc/mjlbach-lint-workflow#32]
### Neovim Version

v4.20

### Operating system/version:

Arch, btw.

### Terminal name/version:

kitty

### TERM environment variable

kitty-256something i can't remember

### Installation

using nix like a chad

### Reproduce

- run nvim -u NORC
- ponder upon your life
- ???
- profit

### 

- [x] Please check the box if it's possible to reproduce the bug with `nvim --clean` as well

### Vim

who knows? can't be bothered to check, vim --version says vim-99

### Expected behavior

my quality of life got better when editing a file inside vim

### Actual behavior

my life stays the same :((

**Comment by dundargoc** [comment]
Discussion way too heated. Locked.
